### ISSUE TITLE
[Question] Is it required to have git CLI installed in order to use this lib?

### ISSUE THREAD

**Issue by albertininm** [seymen/git-last-commit#18]
I'm planning to use this lib, but I need to know if it needs git installed in the machine.
Reading the code it seems that it does require, but maybe there's something behind the scenes that I'm not aware of.
Thank you in advance.

**Comment by seymen** [comment]
Hi @albertmourato - yes it needs git to be installed. It is basically running a git log command in the background with the relevant params (see https://github.com/seymen/git-last-commit/blob/master/source/index.js#L29).

**Comment by albertininm** [comment]
Thank you, @seymen.
Currently I use `isomorphic-git`, which is an awesome lib, but it reads the git `.pack` file in order to extract commit information. It works fine, but this file increases its size too quickly when people push big files to their repo, and it makes `fs` not able to read such a huge file with its maximum buffer, so that the lib fails. I'll use this it as a fallback in case the users don't have git client CLI installed on their machines.

Once again, thank you!
