### ISSUE TITLE
Type declarations should be declared in package.json

### ISSUE THREAD

**Issue by haykam821** [seymen/git-last-commit#28]
According to the [TypeScript handbook](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package), specifying type declarations located at `./index.d.ts` is optional but recommended. However, features like [npm's bundled type indicator](https://github.blog/changelog/2020-12-16-npm-displays-packages-with-bundled-typescript-declarations/) require type declarations to be specified.

**Comment by seymen** [comment]
Would you like to submit a little PR to that effect?
