### ISSUE TITLE
git-tags not shown

### ISSUE THREAD

**Issue by chrisv-dev** [seymen/git-last-commit#3]
I'm using `git tag -a tagname -m "tag description"` to add tags. They are listed when typing `git tag`. Nevertheless they don't show up when using this module. I'd expect them to be located in the object at `{tags:[...]}`

git version: 2.7.4
git-last-commit version: 0.2.0

**Comment by seymen** [comment]
Hi @christw92 

My apologies, projects had no tags!!

I've tagged the source for v0.2.0 now. `git tag` is listing it now.
